install.packages("yearn")
install.packages("https://www.rdocumentation.org/packages/yearn")
library(ape)
library(rotl)
library(phytools)
library(geiger) 
library(OUwie)
library(corHMM)

# Getting data
anole_tree<-read.tree("http://www.phytools.org/eqg2015/data/anole.tre")
anole_tree
plot(anole_tree)
svl <- read.csv("http://www.phytools.org/eqg2015/data/svl.csv",
                row.names=1)
svl <- as.matrix(svl)[,1] #convert dataframe to a vector
svl

# Cleaning data
CleanData <- function(phy, data) {
  treeclean<-geiger::treedata(phy,data)
  return(treeclean)
}
treeclean<-CleanData(anole_tree, svl)

# Visualizing data
VisualizeData<-function(phy,data){
  phytools::contMap(phy,data,plot=TRUE)
}
treecleanvector<-as.vector(treeclean$data)
is.vector(treecleanvector)
names(treecleanvector)<-make.names(row.names(treeclean$data))
VisualizeData(treeclean$phy,treecleanvector)

# Rate of evolution
BM1 <- geiger::fitContinuous(treeclean$phy, treeclean$data, model="BM")
print(paste("The rate of evolution is", BM1$opt$sigsq, "in units of million years"))

OU1 <- fitContinuous(treeclean$phy, treeclean$data, model="OU")
par(mfcol(c(1,2)))
plot(treeclean$phy, show.tip.label=TRUE)
ou.tree <- rescale(treeclean$phy, model="OU", alpha=OU1$opt$alpha)
plot(ou.tree)
#BM model gives shorter branch lengths than OU model. 

# Comparing trees
AIC.BM1 <- BM1$opt$aic
AIC.OU1 <- BM1$opt$aic
delta.AIC.BM1 <- AIC.BM1-min(c(AIC.BM1,AIC.OU1))
delta.AIC.OU1 <- AIC.OU1-min(c(AIC.BM1,AIC.OU1))

# Assigning regimes by estimating ancestral state of a discrete trait
svl1 <- read.csv("http://www.phytools.org/eqg2015/data/svl.csv",
                 header=TRUE,sep=",")
one.discrete.char <-svl1$Dimorph
reconstruction.info <- ace(one.discrete.char, treeclean$phy, type="discrete", method="ML", CI=TRUE)
best.states <- colnames(reconstruction.info$lik.anc)[apply(reconstruction.info$lik.anc, 1, which.max)]

# Adding labels to the tree
plot.phylo(treeclean$phy, show.node.label=TRUE)
nodeBased.OUMV <- OUwie(treeclean$phy, treeclean$data, model="OUMV", simmap.tree=FALSE, diagn=FALSE)
print(nodeBased.OUMV)

# Running OUwie models
models <- c("BM1","BMS","OU1","OUM","OUMV","OUMA","OUMVA")
RunSingleOUwieModel<-function(phy,data,model){
  nodeBased.OUwie<-OUwie(phy,data,model=model,simmap.tree=FALSE,diagn=FALSE)
  return(nodeBased.OUwie)
}
results <- lapply(models, RunSingleOUwieModel, phy=treeclean$phy, data=svl1)

#AIC: Akaike Information Criterion used for selecting a model from a set of models. The best model has ???AIC of 0. 
#AICc: Accounts the sample size.
#BIC: Bayesian Information criterion used for comparing between models. The best model has lower BIC. 
#alpha: Strength of selection 
#lnL: Maximum log-likelihood for the model
#sigma squared: Brownian rate, determines how fast traits will randomly walk through time.  
#theta: Optimal value for the trait

AICc.values<-sapply(results, "[[", "AICc")
names(AICc.values)<-models
AICc.values<-AICc.values-min(AICc.values)
print(AICc.values) #The best model is the one with smallest AICc score
best<-results[[which.min(AICc.values)]] #store for later
print(best) #prints info on best model

# Trying a range of alpha values
alpha.values<-seq(from=0.1, to=5, length.out=50)

likelihood.values <- rep(NA, length(alpha.values))
for (iteration in sequence(length(alpha.values))) {
  likelihood.values[iteration] <- OUwie.fixed(tree, trait, model="OUMV", alpha=rep(alpha.values[iteration],2), sigma.sq=best$solution[2,], theta=best$theta[,1])$loglik
}

plot(x= alpha.values, y= likelihood.values, xlab="Alpha", ylab="log(likelihood)", type="l", bty="n")
points(x=best$solution[1,1], y=best$loglik, pch=16, col="red")
text(x=best$solution[1,1], y=best$loglik, "unconstrained best", pos=4, col="red")

# Two log-likelihood
abline(h=-(best$loglik), lty="dotted")

# Looking at both theta parameters at once
install.packages("akima")
library(akima)
nreps<-400
theta1.points<-c(best$theta[1,1], rnorm(nreps-1, best$theta[1,1], 5*best$theta[1,2])) #center on optimal value, have extra variance
theta2.points<-c(best$theta[2,1], rnorm(nreps-1, best$theta[2,1], 5*best$theta[2,2])) #center on optimal value, have extra variance
likelihood.values<-rep(NA,nreps)
for (iteration in sequence(nreps)) {
  likelihood.values[iteration] <- OUwie.fixed(cleantree$phy, svl1, model="OUMV", alpha=best$solution[1,], sigma.sq=best$solution[2,], theta=c(theta1.points[iteration], theta2.points[iteration]))$loglik
}
likelihood.differences<-(-(likelihood.values-max(likelihood.values)))

# Simulating on the MLE values
interpolated.points<-interp(x=theta1.points, y=theta2.points, z= likelihood.differences, linear=FALSE, extrap=TRUE, xo=seq(min(theta1.points), max(theta1.points), length = 400), yo=seq(min(theta2.points), max(theta2.points), length = 400))
contour(interpolated.points, xlim=range(c(theta1.points, theta2.points)),ylim=range(c(theta1.points, theta2.points)), xlab="Theta 1", ylab="Theta 2", levels=c(2,5,10),add=FALSE,lwd=1, bty="n", asp=1)
points(x=best$theta[1,1], y=best$theta[2,1], col="red", pch=16)
points(x=svl1$X[which(trait$Reg==1)],y=rep(min(c(theta1.points, theta2.points)), length(which(trait$Reg==1))), pch=18, col=rgb(0,0,0,.3)) #the tip values in regime 1, plotted along x axis
points(y=svl1$X[which(trait$Reg==2)],x=rep(min(c(theta1.points, theta2.points)), length(which(trait$Reg==2))), pch=18, col=rgb(0,0,0,.3)) #the tip values in regime 2, plotted along y axis


trait.ordered<-data.frame(svl1[,2], svl1[,2],row.names=svl1[,1])
trait.ordered<- trait.ordered[treeclean$tip.label,]
z<-trait.ordered[,1]
names(z)<-rownames(trait.ordered)
tree.mapped<-make.simmap(treeclean$phy,z,model="ER",nsim=1)
leg<-c("black","red")
names(leg)<-c("Dimorph", "Non-dimorph")
plotSimmap(tree.mapped,leg,pts=FALSE,ftype="off", lwd=1)
simmapBased<-OUwie(tree.mapped,scl1,model="OUMV", simmap.tree=TRUE, diagn=FALSE)
print(simmapBased)
print(best)