install.packages("TreeSim")
install.packages("diversitree")
install.packages("hisse")
library(ape)
library(TreeSim)
library(geiger)
library(diversitree)
library(hisse)

# Looking only at diversification without extinction
my.tree <- TreeSim::sim.bd.taxa(n=300, numbsim=1, lambda=0.1, mu=0)[[1]]
plot(my.tree)

# Plotting the tree
ape::ltt.plot(my.tree)
ape::ltt.plot(my.tree, log="y")

# Looking at multiple trees
yule.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=0.1, mu=0, complete=FALSE)
ape::mltt.plot(yule.trees, log="y")

# Looking at trees with birth and death
bd.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=1, mu=.9, complete=FALSE)
ape::mltt.plot(bd.trees, log="y", legend=FALSE)

#Comparing them
depth.range <- range(unlist(lapply(yule.trees,ape::branching.times)), unlist(lapply(bd.trees,ape::branching.times)))
max.depth <- sum(abs(depth.range)) #ape rescales depths
plot(x=c(0, -1*max.depth), y=c(1, ape::Ntip(yule.trees[[1]])), log="y", type="n", bty="n", xlab="Time", ylab="N")
colors=c(rgb(1,0,0,0.5), rgb(0, 0, 0, 0.5))
list.of.both <- list(bd.trees, yule.trees)
for (i in sequence(2)) {
  tree.list <- list.of.both[[i]]
  for (j in sequence(length(tree.list))) {
    ape::ltt.lines(tree.list[[j]], col=colors[[i]])
  }
}
legend("topleft", legend=c("Birth Death", "Yule"), fill=colors)

# Zooming in on the final part of the plot
depth.range <- range(unlist(lapply(yule.trees,ape::branching.times)), unlist(lapply(bd.trees,ape::branching.times)))
max.depth <- sum(abs(depth.range)) #ape rescales depths
plot(x=c(0, -5), y=c(200, ape::Ntip(yule.trees[[1]])), log="y", type="n", bty="n", xlab="Time", ylab="N")
colors=c(rgb(1,0,0,0.5), rgb(0, 0, 0, 0.5))
list.of.both <- list(bd.trees, yule.trees)
for (i in sequence(2)) {
  tree.list <- list.of.both[[i]]
  for (j in sequence(length(tree.list))) {
    ape::ltt.lines(tree.list[[j]], col=colors[[i]])
  }
}
legend("topleft", legend=c("Birth Death", "Yule"), fill=colors)

# What happens if speciation rate is much higher than extinction rate? How does the simulation change with different values, but keeping their difference constant? If their sum is constant?
my.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=2, mu=0.1, complete=FALSE)
next.trees <- TreeSim::sim.bd.taxa(n=300, numbsim=10, lambda=1.5, mu=0.3, complete=FALSE)
ape::mltt.plot(my.trees, log="y", legend=FALSE)
ape::mltt.plot(next.trees, log="y", legend=FALSE)

# Tree plus trait model: simulating a tree and characters
speciation.rates <- c(0.1, 0.1, 0.1, 0.2) #0A, 1A, 0B, 1B
extinction.rates <- rep(0.03, 4)
transition.rates <- c(0.01,0.01,0, 0.01, 0, 0.01, 0.01,0,0.01, 0,0.01,0.01)
pars <- c(speciation.rates, extinction.rates, transition.rates)
phy <- tree.musse(pars, max.taxa=50, x0=1, include.extinct=FALSE)
sim.dat.true <- data.frame(names(phy$tip.state), phy$tip.state)
sim.dat <- sim.dat.true

# Hiding the "hidden" state
sim.dat[sim.dat[,2]==3,2] = 1
sim.dat[sim.dat[,2]==4,2] = 2

# Converting states 1,2 to 0,1
sim.dat[,2] = sim.dat[,2] - 1
plot(phy)
knitr::kable(cbind(sim.dat, true.char=sim.dat.true$phy.tip.state))

# Index vectors
turnover.anc = c(1,1,0,0)
eps.anc = c(1,1,0,0)

#Separate turnover rates for both states 0A and 1A
turnover.anc = c(1,2,0,0)

# Hisse model corresponds to four separate net turnover rates for 1=0A, 2=1A, 3=0B, 4=1B
turnover.anc = c(1,2,3,4)

# Yule (pure birth) equivalent
eps.anc = c(0,0,0,0)

# Generating index matrix
trans.rates = TransMatMaker(hidden.states=TRUE)
trans.rates

# Using internal function
trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10))
trans.rates.nodual

# Model assuming all transitions equal to one another
trans.rates.nodual.equal16 = ParEqual(trans.rates.nodual, c(1,6))
trans.rates.nodual.equal16

trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal

trans.rates.nodual.allequal = trans.rates.nodual
trans.rates.nodual.allequal[!is.na(trans.rates.nodual.allequal) & !trans.rates.nodual.allequal == 0] = 1
trans.rates.nodual.allequal

# Using BiSSE model in HiSSE
trans.rates.bisse = TransMatMaker(hidden.states=FALSE)
trans.rates.bisse

pp = hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal)

# Diversification parameters
turnover.anc = c(1,2,0,3)
eps.anc = c(1,2,0,3)

trans.rates <- TransMatMaker(hidden.states=TRUE)
trans.rates.nodual.no0B <- ParDrop(trans.rates, c(2,3,5,7,8,9,10,12))
trans.rates.nodual.no0B

# Output net diversification
pp = hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal, output.type="net.div")

# Null-two model
turnover.anc = c(1,1,2,2)
eps.anc = c(1,1,2,2)

trans.rates = TransMatMaker(hidden.states=TRUE)
trans.rates.nodual = ParDrop(trans.rates, c(3,5,8,10))

# All rates assumed equal
trans.rates.nodual.allequal = ParEqual(trans.rates.nodual, c(1,2,1,3,1,4,1,5,1,6,1,7,1,8))
trans.rates.nodual.allequal

# Three rates specification
# Now we want three specific rates:
trans.rates.nodual.threerates <- trans.rates.nodual

# Set all transitions from 0->1 to be governed by a single rate:
to.change <- cbind(c(1,3), c(2,4))
trans.rates.nodual.threerates[to.change] = 1

# Now set all transitions from 1->0 to be governed by a single rate:
to.change <- cbind(c(2,4), c(1,3))
trans.rates.nodual.threerates[to.change] = 2

# Finally, set all transitions between the hidden state to be a single rate (essentially giving you an estimate of the rate by which shifts in diversification occur)
to.change <- cbind(c(1,3,2,4), c(3,1,4,2))
trans.rates.nodual.threerates[to.change] = 3
trans.rates.nodual.threerates

# Transition rate matrix supplied to hisse()
pp = hisse(phy, sim.dat, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover.anc,
           eps.anc=eps.anc, trans.rate=trans.rates.nodual.allequal)

# Loading the file
load("C:/Users/ssapkot1/Documents/Shiwani Working folder/Course Materials/EEB 587/testrecon1.rda")
class(pp.recon)
pp.recon

# Plotting net diversification rate
plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE)

# Visualization of the vector
plot.hisse.states(pp.recon, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072))
pp.recon$aic
pp.recon = MarginRecon(phy, sim.dat, f=c(1,1), hidden.states=TRUE, pars=pp$solution,
                       aic=pp$aic, n.cores=2)

hisse.results.list = list()
load("C:/Users/ssapkot1/Documents/Shiwani Working folder/Course Materials/EEB 587/testrecon1.rda")
hisse.results.list[[1]] = pp.recon
load("C:/Users/ssapkot1/Documents/Shiwani Working folder/Course Materials/EEB 587/testrecon2.rda")
hisse.results.list[[2]] = pp.recon
load("C:/Users/ssapkot1/Documents/Shiwani Working folder/Course Materials/EEB 587/testrecon3.rda")
hisse.results.list[[3]] = pp.recon

# Now supply the list the plotting function
plot.hisse.states(hisse.results.list, rate.param="net.div", show.tip.label=FALSE, rate.range=c(0,0.072))

# First, suck in all the files with .Rsave line ending in your working directory:
files = system("ls -1 | grep .rda", intern=TRUE)

# Create an empty list object
hisse.results.list = list()

# Now loop through all files, adding the embedded pp.recon object in each
for(i in sequence(length(files))){
  load(files[i])
  hisse.results.list[[i]] = pp.recon
  rm(pp.recon)
}

# Working with my data
anole_tree<-read.tree("http://www.phytools.org/eqg2015/data/anole.tre")
anole_tree
svl <- read.csv("http://www.phytools.org/eqg2015/data/svl.csv",
               row.names=1, stringsAsFactors = FALSE)
svl1 <-as.data.frame(svl)

# Tranisition rate matrix and diversification parameters
trans_rates <- hisse::TransMatMaker(hidden.states=TRUE)
trans_rates_nodual_no0B <- hisse::ParDrop(trans_rates, c(2,3,5,7,8,9,10,12))
turnover_anc = c(1,2,0,3)
eps_anc = c(1,2,0,3)

# Hisse  
hissedata <- hisse(anole_tree, svl1, f=c(1,1), hidden.states=TRUE, turnover.anc=turnover_anc, eps.anc=eps_anc, trans.rate=trans_rates_nodual_no0B, output.type="net.div")

# Plotting  
hissedata_r <- hisse::MarginRecon(anole_tree, svl1, f=c(1,1), hidden.states=TRUE, pars=hiseedata$solution, aic=hissedata$aic)
plot.hisse.states(hissedata_r, rate.param="net.div", show.tip.label=FALSE)





